version: '3'

services:
  thyme_and_budget:
    build: .
    restart:
      always
    ports:
      - "9888:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=uqKK42OerZHUkcjBGs8yyntmAuQSA2u3zQ3R5t2zRU4bYXyw6x # Change this to a random string
      - ALLOWED_HOSTS=*
      - USE_X_FORWARDED_HOST=True
      - DB_NAME=thyme_and_budget
      - DB_USER=thyme_and_budget
      - DB_PASSWORD=thyme_and_budget
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - postgres
    networks:
      - dbnet

  postgres:
    image: postgres:16
    restart:
      always
    environment:
      - POSTGRES_USER=thyme_and_budget
      - POSTGRES_PASSWORD=thyme_and_budget
      - POSTGRES_DB=thyme_and_budget
    volumes:
        - dbdata:/var/lib/postgresql/data
    networks:
      - dbnet

volumes:
    dbdata:
networks:
  dbnet: