# Generated by Django 5.0.1 on 2024-02-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('donor', 'DONOR'), ('receiver', 'RECEIVER')], default='donor', max_length=10, null=True),
        ),
    ]
